<a href="https://colab.research.google.com/github/Arbind96/Nlp/blob/main/iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import mpl_toolkits
from google.colab import drive
from sklearn.model_selection import train_test_split

In [29]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [30]:
drive.mount('/content/gdrive')
path="/content/gdrive/MyDrive/DeepLearning/Assignment/iris data.xlsx"

Mounted at /content/gdrive


In [52]:
data= pd.read_excel(path)
data.head()

Sepal length  Sepal width  Petal length  Petal width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [53]:
X = data.iloc[:,0:3].values
y = data.iloc[:,4].values
print(X[0:5])
print(y[0:5])


[[5.1 3.5 1.4]
 [4.9 3.  1.4]
 [4.7 3.2 1.3]
 [4.6 3.1 1.5]
 [5.  3.6 1.4]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [43]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [54]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [55]:
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [56]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [57]:
# Split the data for training and testing
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [58]:
print(X_train[0:5])

[[6.4 3.1 5.5]
 [5.4 3.  4.5]
 [5.2 3.5 1.5]
 [6.1 3.  4.9]
 [6.4 2.8 5.6]]


In [59]:
print(y_train[0:5])

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]]


In [60]:
print(X_test[0:5])

[[5.8 2.8 5.1]
 [6.  2.2 4. ]
 [5.5 4.2 1.4]
 [7.3 2.9 6.3]
 [5.  3.4 1.5]]


In [61]:
print(y_test[0:5])

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]]


In [67]:
from tensorflow.keras.models import Sequential
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dropout

#model = Sequential() #Create your base model
#model.add(Dense(16,activation='relu')) #Add layer with 8 nodes
#model.add(Dropout(0.5))# Add 50% Dropout
#model.add(Dense(3,activation='relu'))
#model.add(Dropout(0.5))
#model.add(Dense(3))
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu',kernel_regularizer='l2'),
    tf.keras.layers.Dense(32, activation='relu',kernel_regularizer='l2'),
    tf.keras.layers.Dense(16, activation='relu',kernel_regularizer='l2'),
    tf.keras.layers.Dense(3, activation='relu')
  ])
#model.compile(optimizer='adam', loss='mse',metrics=['accuracy'])
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [68]:
#model.fit(X_train, y_train, batch_size=50, epochs=100)
model.fit(X_train,y_train,
            validation_data=(X_test,y_test),
            batch_size=20,epochs=100)

Epoch 1/100
6/6 [==============================] - 1s 38ms/step - loss: 5.9733 - accuracy: 0.5083 - val_loss: nan - val_accuracy: 0.3667
Epoch 2/100
6/6 [==============================] - 0s 6ms/step - loss: nan - accuracy: 0.3250 - val_loss: nan - val_accuracy: 0.3667
Epoch 3/100
6/6 [==============================] - 0s 7ms/step - loss: nan - accuracy: 0.3250 - val_loss: nan - val_accuracy: 0.3667
Epoch 4/100
6/6 [==============================] - 0s 7ms/step - loss: nan - accuracy: 0.3250 - val_loss: nan - val_accuracy: 0.3667
Epoch 5/100
6/6 [==============================] - 0s 6ms/step - loss: nan - accuracy: 0.3250 - val_loss: nan - val_accuracy: 0.3667
Epoch 6/100
6/6 [==============================] - 0s 6ms/step - loss: nan - accuracy: 0.3250 - val_loss: nan - val_accuracy: 0.3667
Epoch 7/100
6/6 [==============================] - 0s 8ms/step - loss: nan - accuracy: 0.3250 - val_loss: nan - val_accuracy: 0.3667
Epoch 8/100
6/6 [==============================] - 0s 6ms/step - 

In [70]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: nan
Test accuracy: 0.36666667461395264
